apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: mohamed710/result:0617db23a7a434902f890157e7bddca126ecf601

        name: result
        ports:
        - containerPort: 80
          name: result
