apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: mohamed710/result:2948a010abd7533dbc97a21381ce0ea47f3c3086

        name: result
        ports:
        - containerPort: 80
          name: result
