apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: mohamed710/result:2738445ce0a0eb6030327420e715168698d158c4
        name: result
        ports:
        - containerPort: 80
          name: result
