apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: mohamed710/vote:0617db23a7a434902f890157e7bddca126ecf601
        name: vote
        ports:
        - containerPort: 80
          name: vote
