apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: mohamed710/vote:f1e2a8213a2624a1a257e9203a99a5f30fdc88a6
        name: vote
        ports:
        - containerPort: 80
          name: vote
