apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: mohamed710/vote:2948a010abd7533dbc97a21381ce0ea47f3c3086
        name: vote
        ports:
        - containerPort: 80
          name: vote
